version: "3.8"

services:
  app:
    # container_name: testingUI
    # image: testing
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000